name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: build, pack & publish
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.x
    - name: Publish
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: src/shared/MsSql.Adapter.Collector.Types/MsSql.Adapter.Collector.Types.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
    - name: Cleanup
      run: rm -f *.nupkg *.snupkg